# Generated by Django 4.2.6 on 2023-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_modules_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModules',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewStudents',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('modules', models.ManyToManyField(to='School.newmodules')),
            ],
        ),
    ]
