# Generated by Django 4.2.6 on 2023-10-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_newmodules_newstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneNewStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.modules')),
            ],
        ),
    ]
