# Generated by Django 4.2.6 on 2023-10-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_lastmodules_laststudents_delete_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laststudents',
            name='modules',
        ),
        migrations.DeleteModel(
            name='schools',
        ),
        migrations.DeleteModel(
            name='LastModules',
        ),
        migrations.DeleteModel(
            name='LastStudents',
        ),
    ]
