# Generated by Django 4.2.6 on 2023-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('School', '0007_remove_laststudents_modules_delete_schools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Sch_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
