# Generated by Django 4.2.6 on 2023-10-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=200)),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.school')),
            ],
        ),
    ]
