# Generated by Django 4.2.6 on 2023-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0010_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=200)),
            ],
        ),
    ]
