# Generated by Django 4.2.6 on 2023-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0012_assessment_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('Answer_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=50)),
            ],
        ),
    ]
