# Generated by Django 4.2.6 on 2023-10-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0013_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('Award_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Award', models.CharField(max_length=100)),
            ],
        ),
    ]
