# Generated by Django 4.2.6 on 2023-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0014_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=200)),
            ],
        ),
    ]
