# Generated by Django 4.2.6 on 2023-10-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0019_delete_summery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participants', models.IntegerField()),
                ('sydney_percentile', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.FloatField()),
                ('Correct_Answer', models.CharField(max_length=100)),
                ('participant', models.IntegerField()),
                ('student_score', models.FloatField()),
                ('Year_level_name', models.IntegerField()),
                ('Answer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.answers')),
                ('Assessment_areas_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.assessment_areas')),
                ('Award_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.awards')),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.category')),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.class')),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.school')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.student')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.subject')),
            ],
        ),
    ]
